
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHTB = 28;
  public static final int CONST = 16;
  public static final int GE = 36;
  public static final int ELSIF = 4;
  public static final int LEFTP = 25;
  public static final int INTEGER = 41;
  public static final int SEMI = 23;
  public static final int ARRAY = 7;
  public static final int MINUS = 21;
  public static final int NOT = 39;
  public static final int AND = 38;
  public static final int LEFTB = 27;
  public static final int LT = 33;
  public static final int RECORD = 12;
  public static final int OR = 19;
  public static final int COMMA = 24;
  public static final int DIV = 18;
  public static final int BEGIN = 13;
  public static final int PLUS = 20;
  public static final int ASSIGN = 37;
  public static final int IF = 2;
  public static final int DOT = 29;
  public static final int LE = 34;
  public static final int OF = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOD = 17;
  public static final int EQ = 31;
  public static final int MODULE = 14;
  public static final int TIMES = 22;
  public static final int COLON = 30;
  public static final int ELSE = 3;
  public static final int WHILE = 10;
  public static final int THEN = 5;
  public static final int NE = 32;
  public static final int END = 6;
  public static final int RIGHTP = 26;
  public static final int GT = 35;
  public static final int VAR = 8;
  public static final int PROCEDURE = 15;
  public static final int DO = 11;
  public static final int IDENTIFIER = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "ELSIF",
  "THEN",
  "END",
  "ARRAY",
  "VAR",
  "OF",
  "WHILE",
  "DO",
  "RECORD",
  "BEGIN",
  "MODULE",
  "PROCEDURE",
  "CONST",
  "MOD",
  "DIV",
  "OR",
  "PLUS",
  "MINUS",
  "TIMES",
  "SEMI",
  "COMMA",
  "LEFTP",
  "RIGHTP",
  "LEFTB",
  "RIGHTB",
  "DOT",
  "COLON",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "ASSIGN",
  "AND",
  "NOT",
  "IDENTIFIER",
  "INTEGER"
  };
}

