/* The following code was generated by JFlex 1.4.1 on 17-12-2 下午10:00 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 17-12-2 下午10:00 from the specification file
 * <tt>oberon.flex</tt>
 */
public class OberonScanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  3,  0,  0,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3,  0,  0, 37,  0,  0,  0,  0, 30, 31, 27, 25, 29, 26, 34,  0, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 35, 28, 38, 36, 39,  0, 
     0, 13, 20, 19, 12,  6,  5, 21, 10,  4,  1,  1,  7, 22, 11, 17, 
    24,  1, 14,  8,  9, 23, 16, 18,  1, 15,  1, 32,  1, 33,  1,  1, 
     1, 13, 20, 19, 12,  6,  5, 21, 10,  4,  1,  1,  7, 22, 11, 17, 
    24,  1, 14,  8,  9, 23, 16, 18,  1, 15,  1,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\15\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\4\2\1\24\3\2"+
    "\1\25\1\26\6\2\1\27\1\30\1\31\1\2\1\32"+
    "\1\2\1\33\3\2\1\34\4\2\1\35\2\2\1\36"+
    "\1\37\1\2\1\40\7\2\1\41\1\42\1\2\1\43"+
    "\1\44\1\45\1\46\2\2\1\47\1\2\1\50\1\2"+
    "\1\51\2\2\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258"+
    "\0\u0280\0\u02a8\0\u02a8\0\u02a8\0\u02a8\0\u02a8\0\u02a8\0\u02a8"+
    "\0\50\0\50\0\u02a8\0\u02d0\0\u02a8\0\u02a8\0\u02f8\0\u0320"+
    "\0\50\0\u0348\0\u0370\0\u0398\0\u03c0\0\50\0\u03e8\0\u0410"+
    "\0\u0438\0\50\0\50\0\u0460\0\u0488\0\u04b0\0\u04d8\0\u0500"+
    "\0\u0528\0\u02a8\0\u02a8\0\u02a8\0\u0550\0\50\0\u0578\0\50"+
    "\0\u05a0\0\u05c8\0\u05f0\0\50\0\u0618\0\u0640\0\u0668\0\u0690"+
    "\0\u06b8\0\u06e0\0\u0708\0\50\0\50\0\u0730\0\50\0\u0758"+
    "\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\u0848\0\50\0\50"+
    "\0\u0870\0\50\0\u0898\0\50\0\50\0\u08c0\0\u08e8\0\50"+
    "\0\u0910\0\50\0\u0938\0\50\0\u0960\0\u0988\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\2\1\6\2\2"+
    "\1\7\2\2\1\10\1\11\1\12\1\2\1\13\1\14"+
    "\1\15\1\16\1\17\1\2\1\20\1\2\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\0\2\2"+
    "\1\0\25\2\7\0\2\2\10\0\1\3\50\0\1\4"+
    "\45\0\2\2\1\0\1\2\1\41\23\2\7\0\2\2"+
    "\7\0\2\2\1\0\3\2\1\42\3\2\1\43\15\2"+
    "\7\0\2\2\7\0\2\2\1\0\6\2\1\44\16\2"+
    "\7\0\2\2\7\0\2\2\1\0\1\45\14\2\1\46"+
    "\7\2\7\0\2\2\7\0\2\2\1\0\12\2\1\47"+
    "\12\2\7\0\2\2\7\0\2\2\1\0\2\2\1\50"+
    "\22\2\7\0\2\2\7\0\2\2\1\0\11\2\1\51"+
    "\13\2\7\0\2\2\7\0\2\2\1\0\1\2\1\52"+
    "\10\2\1\53\12\2\7\0\2\2\7\0\2\2\1\0"+
    "\6\2\1\54\3\2\1\55\12\2\7\0\2\2\7\0"+
    "\2\2\1\0\15\2\1\56\7\2\7\0\2\2\7\0"+
    "\2\2\1\0\2\2\1\57\22\2\7\0\2\2\7\0"+
    "\2\2\1\0\15\2\1\60\7\2\7\0\2\2\7\0"+
    "\2\2\1\0\12\2\1\61\12\2\7\0\2\2\122\0"+
    "\1\62\47\0\1\63\47\0\1\64\4\0\2\2\1\0"+
    "\4\2\1\65\20\2\7\0\2\2\7\0\2\2\1\0"+
    "\10\2\1\66\14\2\7\0\2\2\7\0\2\2\1\0"+
    "\2\2\1\67\22\2\7\0\2\2\7\0\2\2\1\0"+
    "\14\2\1\70\10\2\7\0\2\2\7\0\2\2\1\0"+
    "\12\2\1\71\12\2\7\0\2\2\7\0\2\2\1\0"+
    "\11\2\1\72\5\2\1\73\5\2\7\0\2\2\7\0"+
    "\2\2\1\0\12\2\1\74\12\2\7\0\2\2\7\0"+
    "\2\2\1\0\1\75\24\2\7\0\2\2\7\0\2\2"+
    "\1\0\1\76\24\2\7\0\2\2\7\0\2\2\1\0"+
    "\7\2\1\77\15\2\7\0\2\2\7\0\2\2\1\0"+
    "\21\2\1\100\3\2\7\0\2\2\7\0\2\2\1\0"+
    "\10\2\1\101\14\2\7\0\2\2\7\0\2\2\1\0"+
    "\15\2\1\102\7\2\7\0\2\2\7\0\2\2\1\0"+
    "\1\103\1\2\1\104\22\2\7\0\2\2\7\0\2\2"+
    "\1\0\7\2\1\105\15\2\7\0\2\2\7\0\2\2"+
    "\1\0\11\2\1\106\13\2\7\0\2\2\7\0\2\2"+
    "\1\0\10\2\1\107\14\2\7\0\2\2\7\0\2\2"+
    "\1\0\15\2\1\110\7\2\7\0\2\2\7\0\2\2"+
    "\1\0\3\2\1\111\21\2\7\0\2\2\7\0\2\2"+
    "\1\0\5\2\1\112\17\2\7\0\2\2\7\0\2\2"+
    "\1\0\4\2\1\113\20\2\7\0\2\2\7\0\2\2"+
    "\1\0\1\114\24\2\7\0\2\2\7\0\2\2\1\0"+
    "\23\2\1\115\1\2\7\0\2\2\7\0\2\2\1\0"+
    "\17\2\1\116\5\2\7\0\2\2\7\0\2\2\1\0"+
    "\1\2\1\117\23\2\7\0\2\2\7\0\2\2\1\0"+
    "\13\2\1\120\11\2\7\0\2\2\7\0\2\2\1\0"+
    "\12\2\1\121\12\2\7\0\2\2\7\0\2\2\1\0"+
    "\2\2\1\122\22\2\7\0\2\2\7\0\2\2\1\0"+
    "\2\2\1\123\22\2\7\0\2\2\7\0\2\2\1\0"+
    "\5\2\1\124\17\2\7\0\2\2\7\0\2\2\1\0"+
    "\7\2\1\125\15\2\7\0\2\2\7\0\2\2\1\0"+
    "\3\2\1\126\21\2\7\0\2\2\7\0\2\2\1\0"+
    "\2\2\1\127\22\2\7\0\2\2\7\0\2\2\1\0"+
    "\10\2\1\130\14\2\7\0\2\2\7\0\2\2\1\0"+
    "\3\2\1\131\21\2\7\0\2\2\7\0\2\2\1\0"+
    "\2\2\1\132\22\2\7\0\2\2\7\0\2\2\1\0"+
    "\10\2\1\133\14\2\7\0\2\2\7\0\2\2\1\0"+
    "\7\2\1\134\15\2\7\0\2\2\7\0\2\2\1\0"+
    "\23\2\1\135\1\2\7\0\2\2\7\0\2\2\1\0"+
    "\12\2\1\136\12\2\7\0\2\2\7\0\2\2\1\0"+
    "\2\2\1\137\22\2\7\0\2\2\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2480];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\21\1\7\11\2\1\1\11\1\1\2\11\23\1\3\11"+
    "\53\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline+1, yycolumn+1);
    }

    private Symbol symbol(int type, String value) {
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OberonScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public OberonScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 30: 
          { return symbol(Type.ELSE);
          }
        case 43: break;
        case 36: 
          { return symbol(Type.WRITE);
          }
        case 44: break;
        case 31: 
          { return symbol(Type.THEN);
          }
        case 45: break;
        case 3: 
          { return symbol(Type.INTEGER, yytext());
          }
        case 46: break;
        case 40: 
          { return symbol(Type.MODULE);
          }
        case 47: break;
        case 23: 
          { return symbol(Type.ASSIGN);
          }
        case 48: break;
        case 7: 
          { return symbol(Type.SEMI);
          }
        case 49: break;
        case 39: 
          { return symbol(Type.RECORD);
          }
        case 50: break;
        case 38: 
          { return symbol(Type.BEGIN);
          }
        case 51: break;
        case 20: 
          { return symbol(Type.DO);
          }
        case 52: break;
        case 12: 
          { return symbol(Type.RIGHTB);
          }
        case 53: break;
        case 19: 
          { return symbol(Type.IF);
          }
        case 54: break;
        case 32: 
          { return symbol(Type.READ);
          }
        case 55: break;
        case 13: 
          { return symbol(Type.DOT);
          }
        case 56: break;
        case 2: 
          { return symbol(Type.IDENTIFIER, yytext());
          }
        case 57: break;
        case 34: 
          { return symbol(Type.ARRAY);
          }
        case 58: break;
        case 22: 
          { return symbol(Type.OR);
          }
        case 59: break;
        case 15: 
          { return symbol(Type.EQ);
          }
        case 60: break;
        case 11: 
          { return symbol(Type.LEFTB);
          }
        case 61: break;
        case 16: 
          { return symbol(Type.BASE);
          }
        case 62: break;
        case 42: 
          { return symbol(Type.PROCEDURE);
          }
        case 63: break;
        case 6: 
          { return symbol(Type.TIMES);
          }
        case 64: break;
        case 14: 
          { return symbol(Type.COLON);
          }
        case 65: break;
        case 33: 
          { return symbol(Type.ELSIF);
          }
        case 66: break;
        case 26: 
          { return symbol(Type.END);
          }
        case 67: break;
        case 35: 
          { return symbol(Type.WHILE);
          }
        case 68: break;
        case 25: 
          { return symbol(Type.GE);
          }
        case 69: break;
        case 10: 
          { return symbol(Type.RIGHTP);
          }
        case 70: break;
        case 27: 
          { return symbol(Type.DIV);
          }
        case 71: break;
        case 24: 
          { return symbol(Type.LE);
          }
        case 72: break;
        case 29: 
          { return symbol(Type.MOD);
          }
        case 73: break;
        case 5: 
          { return symbol(Type.MINUS);
          }
        case 74: break;
        case 21: 
          { return symbol(Type.OF);
          }
        case 75: break;
        case 9: 
          { return symbol(Type.LEFTP);
          }
        case 76: break;
        case 4: 
          { return symbol(Type.PLUS);
          }
        case 77: break;
        case 18: 
          { return symbol(Type.GT);
          }
        case 78: break;
        case 37: 
          { return symbol(Type.CONST);
          }
        case 79: break;
        case 28: 
          { return symbol(Type.VAR);
          }
        case 80: break;
        case 8: 
          { return symbol(Type.COMMA);
          }
        case 81: break;
        case 41: 
          { return symbol(Type.WRITELN);
          }
        case 82: break;
        case 17: 
          { return symbol(Type.LT);
          }
        case 83: break;
        case 1: 
          { 
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return symbol(Type.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
